from langchain.agents import create_agent

from agents.answer_generator_agent.prompt import SYSTEM_PROMPT, build_user_prompt
from config.logger import get_logger
from providers.llm import LLMProvider


class AnswerGeneratorAgent:
    """Generate a final answer from the reasoning agent response."""

    def __init__(self) -> None:
        self.logger = get_logger(__name__)
        self.chat_model = LLMProvider().get_chat_model()
        self.agent = create_agent(
            model=self.chat_model,
            tools=[],
            system_prompt=SYSTEM_PROMPT,
        )

    def generate(self, user_query: str, reasoning_response: str) -> str:
        """Return the final response for the user."""
        prompt = build_user_prompt(user_query, reasoning_response)
        result = self.agent.invoke(
            {"messages": [{"role": "user", "content": prompt}]}
        )

        output = result.get("output", "")
        if output:
            return output

        if isinstance(result.get("messages"), list) and result["messages"]:
            last_message = result["messages"][-1]
            return getattr(last_message, "content", "") or last_message.get(
                "content", ""
            )

        return "No response generated by answer agent."
