from __future__ import annotations

from langchain.agents import create_agent
from typing import Any, Dict

from agents.llm_reasoning.prompt import SYSTEM_PROMPT, build_user_prompt
from config.logger import get_logger
from providers.llm import LLMProvider
from agents.llm_reasoning.tools import duckduckgo_search


logger = get_logger(__name__)


class LLMReasoningAgent:
    """Answer questions using retrieval results and optional web search."""

    def __init__(self) -> None:
        self.logger = get_logger(__name__)
        self.chat_model = LLMProvider().get_chat_model()
        self.agent = create_agent(
            model=self.chat_model,
            tools=[duckduckgo_search],
            system_prompt=SYSTEM_PROMPT,
        )

    def answer(self, user_query: str, retrieval_payload: Dict[str, Any]) -> str:
        """Return a reasoned answer using retrieval results and optional search."""
        prompt = build_user_prompt(user_query, retrieval_payload)
        result = self.agent.invoke(
            {"messages": [{"role": "user", "content": prompt}]}
        )

        output = result.get("output", "")
        if output:
            return output

        if isinstance(result.get("messages"), list) and result["messages"]:
            last_message = result["messages"][-1]
            return getattr(last_message, "content", "") or last_message.get(
                "content", ""
            )

        return "No response generated by reasoning agent."
