from __future__ import annotations

from typing import Any, Dict

from agents.llm_reasoning.prompt import SYSTEM_PROMPT, build_user_prompt
from config.logger import get_logger
from providers.llm import LLMProvider
from agents.llm_reasoning.tools import duckduckgo_search


logger = get_logger(__name__)


class LLMReasoningAgent:
    """Answer questions using retrieval results and optional web search."""

    def __init__(self) -> None:
        self.logger = get_logger(__name__)
        self.chat_model = LLMProvider().get_chat_model()

    def _needs_web_search(self, retrieval_payload: Dict[str, Any]) -> bool:
        count = retrieval_payload.get("count", 0)
        return count == 0

    def answer(self, user_query: str, retrieval_payload: Dict[str, Any]) -> str:
        """Return a reasoned answer using retrieval results and optional search."""
        web_results = []
        if self._needs_web_search(retrieval_payload):
            web_results = duckduckgo_search(user_query, max_results=5)

        prompt = build_user_prompt(user_query, retrieval_payload, web_results)
        result = self.chat_model.invoke(
            [{"role": "system", "content": SYSTEM_PROMPT},
             {"role": "user", "content": prompt}]
        )
        return getattr(result, "content", "") or "No response generated by reasoning agent."
